export type IndicatorsIds = 'CAPACITY_SHARING_FOR_DEVELOPMENT' | 'INNOVATION_DEV' | 'KNOWLEDGE_PRODUCT' | 'POLICY_CHANGE' | 'OICR' | 'INNOVATION_USE';
export const IndicatorsIdsObject: Record<IndicatorsIds, number> = {
  CAPACITY_SHARING_FOR_DEVELOPMENT: 1,
  INNOVATION_DEV: 2,
  KNOWLEDGE_PRODUCT: 3,
  POLICY_CHANGE: 4,
  OICR: 5,
  INNOVATION_USE: 6
};
