name: SonarCloud Analysis

on:
  push:
    branches:
      - AC-410-First-testing-Enhancements-soanr # Executes on this specific branch
  pull_request:
    branches:
      - AC-410-First-testing-Enhancements-soanr # Also configure for Pull Requests to this branch

jobs:
  sonarcloud:
    runs-on: ubuntu-latest # Use the latest Ubuntu image for the job

    steps:
      # Step 1: Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: "17" # Specify the version of Java you want to use
          distribution: "adoptopenjdk" # Use 'adoptopenjdk' instead of 'adoptium'

      # Step 2: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 3: Install Angular dependencies
      - name: Install dependencies
        run: |
          npm install -g @angular/cli  # Install Angular CLI globally if it's not installed
          npm install  # Install project dependencies

      # Step 4: Run the build and SonarCloud analysis
      - name: Run SonarCloud analysis
        run: |
          npm run build -- --prod  # Build the Angular project for production
          sonar-scanner  # Execute SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Use SonarCloud token from GitHub secrets
