name: Unit Tests

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main
      - dev
      - dev-general-adjustments
      - staging-unit-test

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./research-indicators

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./research-indicators/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./research-indicators

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./research-indicators/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Ensure jq is installed
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Download environment files from AWS Secrets Manager
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws secretsmanager get-secret-value \
            --secret-id dev/app/frontend/alliance/reportingtool \
            --query SecretString \
            --output text > src/environments/environment.ts

          cp src/environments/environment.ts src/environments/environment.dev.ts

      - name: Run unit tests
        run: npm run test

      - name: Upload test coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: research-indicators/coverage/
          retention-days: 30

  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./research-indicators

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "./research-indicators/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Install AWS CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip jq
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Download environment files from AWS Secrets Manager
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws secretsmanager get-secret-value \
            --secret-id dev/app/frontend/alliance/reportingtool \
            --query SecretString \
            --output text > src/environments/environment.ts

          cp src/environments/environment.ts src/environments/environment.dev.ts

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: research-indicators/dist/
          retention-days: 30
